spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/bishe?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 11111
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
    publisher-returns: true

dubbo:
  application:
    id: Scheduler1
    name: dobbo-Scheduler1
  registry:
    address: zookeeper://192.168.206.129:2181?backup=192.168.206.128:2181
  protocol:
    name : dubbo
    port : 20880
  scan : com.seu.cwg.RPC



  freemarker:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.seu.cwg.Bean
