spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/bishe?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 11111
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
    publisher-returns: true



  freemarker:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.seu.cwg.Bean
